### ISSUE TITLE
Issue with opamp and PWM generating IC

### ISSUE THREAD

**Issue by zubenelacribi** [radostin-stefanov/push-up-magnetic-levitation#3]
We are trying the circuit described in this video for some time now:

https://www.youtube.com/watch?v=LaGv2FHS5zg

The principles and the circuit are very well described, so we began to experiment with KA7500C -- the IC which generates PWM in response to the input voltage. The PWM's frequency is determined by the RC time constant with external resistor and capacitor. We use 2 linear Hall effect sensors and subtract their voltages with an opamp, so that we cancel the noise coming from the coil. The result voltage is fed to the PWM generator which determines the width of the impulses. We also use a linear potentiometer to bias the input signal and change the impulse width -- the width corresponds to the distance of the magnet from the coil, so we actually define the distance by turning the potentiometer.

The advantage of the circuit is that it is simple and we don't use a microcontroller.

There were however several issues with it -- it requires multiple power supplies because our sensors work at 6V max while the opamp (LM741 or OP07) require positive and negative voltage for power supply (equivalent to 2 power supplies because we need also 0V for the signal's ground). The coil may use a different power supply because it introduces noises to the circuit.

The minimum voltage for the opamp is +3V and -3V. We took a computer power supply, so we use the +5V and -5V leads. We use 0V and +5V to power the sensors and we definitely need the midpoint (i.e. 0V) for signal ground, otherwise the opamp doesn't operate properly. In this configuration the opamp acts as a subtractor with no amplification (all resistors are 10k, output to input ratio is 1:1). We supply KA7500C with the result signal.

Now follows the issue with KA7500C -- it should use 0V and a positive voltage as a power supply. We mistakenly powered it with +5V but we should use at least +7V by specification (the closest we can use is +12V). It should receive positive voltage from the amplifier, so it does matter how we connect the sensors and what is the direction of the magnet's north pole.

After figuring out all these details, it seems that there is no issue after all, we just have to use multiple voltages: +5V and -5V for the opamp, 0V and +5V for the Hall effect sensors, 0V and +12V for the PWM IC, and again 0V and +12V for the coil (we use electrolytic capacitors to reduce the noise from the coil). The transistor's drain which switches the current through the coil on and off is connected to 0V since the switching voltage (~2V) measures between the gate and the drain (we can't use -12V and +12V for the coil because the transistor will be always on).

So this is the configuration which we should try. The issue from yesterday was that the output of the PWM IC was either constant 0, or constant 1, no impulses were generated. After supplying the right voltage, we expect to see impulses on the oscilloscope like in the video.

**Comment by zubenelacribi** [comment]
While looking at the video again, it appears that there is a single power supply and the 741 opamp is connected to +10V and 0V. Bearing in mind that his sensors can operate at 10V and their neutral point is the supplied voltage divided by 2 (i.e. 5V), it actually makes sense to use a single power supply both for the opamp and the sensors (we can't do this with ours, unfortunately). Not sure how the output signal is generated -- towards 0V or towards the midpoint (5V). Maybe the signal's ground is 5V because the guy on the video connects KA7500C to the same power supply, so the chip receives 5V (if there is no influence from the magnet) which corresponds to 50% duty cycle on the output signal with no bias to the input signal.

He also uses the same power supply for the coil which makes the setup very convenient.

The reason we can't reproduce his experiment is that our sensors cannot operate at 10V, so we should make magic with voltages. I'm not convinced any more that the setup with +5V and -5V for the opamp and 0V and +12V for KA7500C will work. Maybe if we find linear Hall effect sensors which can operate on greater voltage will make our lives easier.

**Comment by zubenelacribi** [comment]
The Hall effect sensors used in the video are SS494B which operate at 4.5-10.5V.

I don't think that the supply voltage is that important since we use the difference between the voltages of the 2 sensors and it can be amplified as much as we want.

Today I tried with 0V and +5V for the sensors and 0V and +12V for the rest of the circuit. In order to make the amplifier work, I used a midpoint between 0V and 12V for the signal ground (i.e. 6V) and the amplifier worked. The generated voltage was passed to the PWM chip and it generated some impulses, although I couldn't change their width by moving the magnet. The width of the impulses changed by biasing the signal with voltage from the potentiometer which may mean that the signal from the sensors is too weak. Also the transistor was always on, no matter what the level of the signal to its gate is.

So there seem to be 2 issues:
  * the signal coming to the PWM chip is too weak -- we should amplify the difference of the signals coming from the sensors (e.g. by factor 2.2).
  * the transistor is always switched on -- there shouldn't be voltage between the drain and the gate when the signal level is 0V, so we should check why the transistor is switched on.

**Comment by zubenelacribi** [comment]
I've forgotten the pull-down 1k resistor to the gate of the transistor, that's why it doesn't switch off :)

**Comment by borisov-r** [comment]
https://ocw.mit.edu/ans7870/8/8.02T/f04/visualizations/faraday/01-FallingRing/01-Falling_Ring320.html

**Comment by zubenelacribi** [comment]
I saw something similar yesterday:

https://ibin.co/33E9h7KwBxg1.jpg

:)))

**Comment by zubenelacribi** [comment]
I noticed that my resistor divider wasn't implemented correctly and fixed it. I began to receive impulses like in video but the logic was reversed in the beginning -- the electromagnet was turned off when moving the magnet away and was turned on when approaching. This was fixed and I now turn the electromagnet on and off correctly. It's just the transistor that denies to operate properly. It's AP9970GT and its threshold voltage is 2-4V. It receives 12V at the gate, so it should turn on, but the voltage between the source and the drain is 1.1V. About 6V falls on the resistor and 2V in the coil. The difference to 12V disappears somewhere, most likely as heat loss.

Not sure if this is ok. If such an amount of the voltage falls on the transistor then its resistance is high, which means it's not completely switched on. It heats up fast like the resistor (actually they are two 10-ohm resistors in parallel rated at 10W). The current which flows through the resistor, the coil and the transistor is 1.3A.

Now the pull-down resistor is present at the gate but it doesn't seem that the transistor controls the current through the coil. It's more like the current flows continuously because even though the voltage to the gate drops to 0 when the magnet is near enough, the electromagnet keeps attracting the magnet, so no hanging in the air is observed, the magnet just sticks. No alternating electromagnetic field can be felt when holding the neodymimum magnet close to the electromagnet.

**Comment by zubenelacribi** [comment]
The Hall effect sensor on the other side of the electromagnet detects no fluctuations when impulses are fed to the gate of the transistor, just the sensor's voltage jumps a little bit which means that electrical current flows continuously through the coil without any switching of the current. The transistor passes the current without any control. It's internal resistance is high and doesn't change with feeding signals on its gate. I'll check whether it has burnt (i.e. whether it has become a resistor).

**Comment by zubenelacribi** [comment]
I tried a simple LED switching circuit with the transistor and connected its gate through 1.6k resistor to ground but it didn't turn off the LED. Even connecting its gate directly to the ground doesn't switch the circuit off. Tried with another such transistor -- it's the same. Tried with IRF3205 (N-channel, drain-source voltage -- 20V, gate-source threshold voltage 2-4V) -- totally the same. I can't switch the circuit off with these transistors.

**Comment by zubenelacribi** [comment]
Ok, I've swapped the place of the source and the drain :)))
If the transistor is properly connected, it switches the circuit on and off as expected. So the LED lit and the coil was attracting and non-attracting according to the level of the signal.
The coil goes to the DRAIN and the SOURCE goes to the ground.

Now the levitation works and the distance to the electromagnet can be adjusted via the potentiometer. The magnet hangs below the electromagnet nicely:

https://ibin.co/33EAdoYB0yaB.jpg

Success!
Issue closed.

**Comment by borisov-r** [comment]
if you are using proto board the problem is the source resistance. a proper
board might needed.

**Comment by zubenelacribi** [comment]
We'll make one.
